let edata = [
    { id: 1, name: "Kelly", email: "kmongin0@newyorker.com", loc: "Batulawang" },
    { id: 2, name: "Xylia", email: "xheam1@gizmodo.com", loc: "Paulínia" },
    { id: 3, name: "Karlen", email: "kvezey2@disqus.com", loc: "Mallawī" },
    { id: 4, name: "Danita", email: "dhumes3@furl.net", loc: "Zuocun" },
    { id: 5, name: "Berti", email: "bmusk4@lycos.com", loc: "Verblyany" },
    { id: 6, name: "Lyn", email: "ldrever5@skyrock.com", loc: "Leidschendam" },
    { id: 7, name: "Marven", email: "mbroady6@usgs.gov", loc: "Lubuk Sikaping" },
    {
      id: 8,
      name: "Oby",
      email: "obirtchnell7@desdev.cn",
      loc: "Maloyaroslavets",
    },
    { id: 9, name: "Jasmin", email: "jdimitriev8@nyu.edu", loc: "Picos" },
    {
      id: 10,
      name: "Barbe",
      email: "bohengerty9@skype.com",
      loc: "Mehmand Chak",
    },
    {
      id: 11,
      name: "Aimee",
      email: "adidelloa@princeton.edu",
      loc: "Barakī Barak",
    },
    { id: 12, name: "Darcy", email: "ddarbonb@wired.com", loc: "Brwinów" },
    { id: 13, name: "Sharron", email: "srobec@live.com", loc: "Pantenan" },
    {
      id: 14,
      name: "Kaela",
      email: "khasleyd@usgs.gov",
      loc: "Paso de Carrasco",
    },
    { id: 15, name: "Aundrea", email: "aepinoye@goodreads.com", loc: "Bogojevo" },
    { id: 16, name: "Lorne", email: "ldorneyf@webs.com", loc: "Hongdu" },
    { id: 17, name: "Anett", email: "agraysong@godaddy.com", loc: "Bangbayang" },
    {
      id: 18,
      name: "Bryanty",
      email: "bmandreh@networksolutions.com",
      loc: "Punta de Bombón",
    },
    { id: 19, name: "Kingsly", email: "koshesnani@usda.gov", loc: "Gogosuket" },
    {
      id: 20,
      name: "Tyne",
      email: "tornillosj@dmoz.org",
      loc: "Ban Khlong Bang Sao Thong",
    },
    {
      id: 21,
      name: "Daron",
      email: "dheinekek@merriam-webster.com",
      loc: "Lucapon",
    },
    { id: 22, name: "Geri", email: "glutasl@ucla.edu", loc: "Holoubkov" },
    {
      id: 23,
      name: "Robinia",
      email: "rstairm@squarespace.com",
      loc: "Dolgoprudnyy",
    },
    { id: 24, name: "Packston", email: "pwoakesn@woothemes.com", loc: "Turba" },
    { id: 25, name: "Eudora", email: "eackredo@samsung.com", loc: "Ílion" },
  ];
  
  export default edata;